title: Manuals
description: The collection of manuals for the software developed at the Lab for Big Data Methodology at the University of Notre Dame.
theme: just-the-docs

url: https://manuals.psychstat.org

favicon_ico: "/assets/images/favicon.ico"

site.author: Lab for Big Data Methodology
site.description: by

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/johnnyzhz/johnnyzhz.github.io

  
