title: Manuals
description: The collection of manuals for the software developed at the Lab for Big Data Methodology at the University of Notre Dame.
theme: just-the-docs

url: https://manuals.psychstat.org

